    1 pft_status_data
      2 status = c1
      2 subeventstatus [* ]
        3 status = c1
        3 table_name = vc
        3 pk_values = vc
    1 mod_objs [* ]
      2 entity_type = vc
      2 mod_recs [* ]
        3 table_name = vc
        3 pk_values = vc
        3 mod_flds [* ]
          4 field_name = vc
          4 field_type = vc
          4 field_value_obj = vc
          4 field_value_db = vc
    1 failure_stack
      2 failures [* ]
        3 programname = vc
        3 routinename = vc
        3 message = vc

